In [11]:
import pandas as pd

# Load the .data file into a pandas DataFrame
df = pd.read_csv('pima-indians-diabetes.data', header=None)

df.head(20)

     0    1   2   3    4          5      6   7    8
0    6  148  72  35  155  33.600000  0.627  50  yes
1    1   85  66  29  155  26.600000  0.351  31   no
2    8  183  64  29  155  23.300000  0.672  32  yes
3    1   89  66  23   94  28.100000  0.167  21   no
4    0  137  40  35  168  43.100000  2.288  33  yes
5    5  116  74  29  155  25.600000  0.201  30   no
6    3   78  50  32   88  31.000000  0.248  26  yes
7   10  115  72  29  155  35.300000  0.134  29   no
8    2  197  70  45  543  30.500000  0.158  53  yes
9    8  125  96  29  155  32.457464  0.232  54  yes
10   4  110  92  29  155  37.600000  0.191  30   no
11  10  168  74  29  155  38.000000  0.537  34  yes
12  10  139  80  29  155  27.100000  1.441  57   no
13   1  189  60  23  846  30.100000  0.398  59  yes
14   5  166  72  19  175  25.800000  0.587  51  yes
15   7  100  72  29  155  30.000000  0.484  32  yes
16   0  118  84  47  230  45.800000  0.551  31  yes
17   7  107  74  29  155  29.600000  0.254  31  yes
18   1  103  30  38   83  43.300000  0.183  33   no
19   1  115  70  30   96  34.600000  0.529  32  yes

In [12]:
# Store the DataFrame as a CSV file
df.to_csv('pima.csv', index=False)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       768 non-null    int64
 1   1       768 non-null    int64
 2   2       768 non-null    int64
 3   3       768 non-null    int64
 4   4       768 non-null    int64
 5   5       768 non-null    float64
 6   6       768 non-null    float64
 7   7       768 non-null    int64
 8   8       768 non-null    object
dtypes: float64(2), int64(6), object(1)
memory usage: 54.1+ KB

In [5]:
from sklearn.preprocessing import StandardScaler


# Get the list of numerical column names
num_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()

# Initialize a StandardScaler object to normalize the numerical columns
scaler = StandardScaler()

# Fit the scaler to the numerical columns
scaler.fit(df[num_cols])

# Transform the numerical columns using the scaler
df[num_cols] = scaler.transform(df[num_cols])

In [6]:
df.head()

,0,1,2,3,4,5,6,7,8
0,0.639947,0.865254,-0.031990,0.670643,-0.003310,0.166292,0.468492,1.425995,yes
1,-0.844885,-1.206013,-0.528319,-0.012301,-0.003310,-0.852531,-0.365061,-0.190672,no
2,1.233880,2.015957,-0.693761,-0.012301,-0.003310,-1.332833,0.604397,-0.105584,yes
3,-0.844885,-1.074504,-0.528319,-0.695245,-0.721243,-0.634212,-0.920763,-1.041549,no
4,-1.141852,0.503604,-2.679076,0.670643,0.149692,1.548980,5.484909,-0.020496,yes

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       768 non-null    float64
 1   1       768 non-null    float64
 2   2       768 non-null    float64
 3   3       768 non-null    float64
 4   4       768 non-null    float64
 5   5       768 non-null    float64
 6   6       768 non-null    float64
 7   7       768 non-null    float64
 8   8       768 non-null    object
dtypes: float64(8), object(1)
memory usage: 54.1+ KB

In [8]:
df.to_csv('pima.csv', index=False)

In [2]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold

# Load the original Pima dataset
df = pd.read_csv("pima.csv")

# Define the number of folds
n_folds = 10

# Use StratifiedKFold to split the data into 10 folds
skf = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=42)

# Create a new DataFrame to hold the folds
fold_df = pd.DataFrame(columns=["Fold", "Contents"])

# Iterate over the folds and store them in fold_df
for fold_idx, (train_idx, test_idx) in enumerate(skf.split(df, df["class"])):
    # Get the name of the current fold
    fold_name = f"fold{fold_idx + 1}"
    
    # Get the contents of the current fold
    fold_contents = "\n".join(df.iloc[test_idx].astype(str).apply(lambda x: ",".join(x), axis=1).values)
    
    # Add the fold to fold_df
    fold_df = fold_df.append({"Fold": fold_name, "Contents": fold_contents}, ignore_index=True)

# Save fold_df to pima-folds.csv
fold_df.to_csv("pima-folds.csv", index=False)

C:\Users\Melo\AppData\Local\Temp\ipykernel_31156\2758524615.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fold_df = fold_df.append({"Fold": fold_name, "Contents": fold_contents}, ignore_index=True)
C:\Users\Melo\AppData\Local\Temp\ipykernel_31156\2758524615.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fold_df = fold_df.append({"Fold": fold_name, "Contents": fold_contents}, ignore_index=True)
C:\Users\Melo\AppData\Local\Temp\ipykernel_31156\2758524615.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fold_df = fold_df.append({"Fold": fold_name, "Contents": fold_contents}, ignore_index=True)
C:\Users\Melo\AppData\Local\Temp\ipykernel_31156\2758524615.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fold_df = fold_df.append({"Fold": fold_name, "Contents": fold_contents}, ignore_index=True)
C:\Users\Melo\AppData\Local\Temp\ipykernel_31156\2758524615.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fold_df = fold_df.append({"Fold": fold_name, "Contents": fold_contents}, ignore_index=True)
C:\Users\Melo\AppData\Local\Temp\ipykernel_31156\2758524615.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fold_df = fold_df.append({"Fold": fold_name, "Contents": fold_contents}, ignore_index=True)
C:\Users\Melo\AppData\Local\Temp\ipykernel_31156\2758524615.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fold_df = fold_df.append({"Fold": fold_name, "Contents": fold_contents}, ignore_index=True)
C:\Users\Melo\AppData\Local\Temp\ipykernel_31156\2758524615.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fold_df = fold_df.append({"Fold": fold_name, "Contents": fold_contents}, ignore_index=True)
C:\Users\Melo\AppData\Local\Temp\ipykernel_31156\2758524615.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fold_df = fold_df.append({"Fold": fold_name, "Contents": fold_contents}, ignore_index=True)
C:\Users\Melo\AppData\Local\Temp\ipykernel_31156\2758524615.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fold_df = fold_df.append({"Fold": fold_name, "Contents": fold_contents}, ignore_index=True)

In [15]:
from sklearn.neighbors import KNeighborsClassifier

def classify_nn(training_filename, testing_filename, k):
    with open(training_filename, 'r') as f:
        training_data = []
        for line in f:
            example = tuple(line.strip().split(','))
            training_data.append(example)
        X_train = []
        y_train = []
        for example in training_data:
            X_train.append(list(map(float, example[:-1])))
            y_train.append(example[-1])
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    with open(testing_filename, 'r') as f:
        testing_data = []
        for line in f:
            example = tuple(line.strip().split(','))
            testing_data.append(example)
        X_test = []
        for example in testing_data:
            X_test.append(list(map(float, example)))
    y_pred = knn.predict(X_test)
    counts = {}
    max_count = 0
    for label in y_pred:
        if label in counts:
            counts[label] += 1
        else:
            counts[label] = 1
        if counts[label] > max_count:
            max_count = counts[label]
    if len(counts) == 1:
        results = [str(label) for label in y_pred]
    else:
        max_labels = []
        for label, count in counts.items():
            if count == max_count:
                max_labels.append(label)
        if len(max_labels) == 1:
            results = [str(label) for label in y_pred]
        else:
            results = []
            for label in y_pred:
                if label in max_labels:
                    results.append(str(label))
                else:
                    results.append('Yes')
    return results

In [16]:
import numpy as np
from sklearn.naive_bayes import GaussianNB

def classify_nb(training_filename, testing_filename):
    with open(training_filename) as f:
        training_data = []
        for line in f.readlines():
            training_data.append(line.strip().split(","))
        X_train = []
        y_train = []
        for row in training_data[1:]:
            X_train.append(list(map(float, row[:-1])))
            y_train.append(row[-1])
        X_train = np.array(X_train)
        y_train = np.array(y_train)
        clf = GaussianNB()
        clf.fit(X_train, y_train)
    with open(testing_filename) as f:
        testing_data = []
        for line in f.readlines():
            testing_data.append(line.strip().split(","))
        X_test = []
        for row in testing_data:
            X_test.append(list(map(float, row)))
        X_test = np.array(X_test)
        y_pred = clf.predict_proba(X_test)
        results = []
        for prediction in y_pred:
            if prediction[0] > prediction[1]:
                results.append("no")
            elif prediction[0] < prediction[1]:
                results.append("yes")
            else:
                results.append("yes")
        return results

In [24]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# Load the Pima Indians Diabetes dataset
pima = pd.read_csv('pima.csv')
X = pima.drop('class', axis=1).values
y = pima['class'].values

# Define the models
models = [('1-NN', KNeighborsClassifier(n_neighbors=1)),
          ('5-NN', KNeighborsClassifier(n_neighbors=5)),
          ('Naive Bayes', GaussianNB())]

# Perform 10-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=3308)
for name, model in models:
    scores = []
    for train_index, test_index in kfold.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        scores.append(accuracy_score(y_test, y_pred))
    print(f'{name} accuracy: {np.mean(scores):.3f} (std: {np.std(scores):.3f})')

1-NN accuracy: 0.686 (std: 0.065)
5-NN accuracy: 0.749 (std: 0.049)
Naive Bayes accuracy: 0.744 (std: 0.055)

In [25]:
# Load the Pima Indians Diabetes dataset
pima = pd.read_csv('pima-CFS.csv')
X = pima.drop('class', axis=1).values
y = pima['class'].values

# Define the models
models = [('1-NN', KNeighborsClassifier(n_neighbors=1)),
          ('5-NN', KNeighborsClassifier(n_neighbors=5)),
          ('Naive Bayes', GaussianNB())]

# Perform 10-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=3308)
for name, model in models:
    scores = []
    for train_index, test_index in kfold.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        scores.append(accuracy_score(y_test, y_pred))
    print(f'{name} accuracy: {np.mean(scores):.3f} (std: {np.std(scores):.3f})')

1-NN accuracy: 0.685 (std: 0.047)
5-NN accuracy: 0.737 (std: 0.040)
Naive Bayes accuracy: 0.766 (std: 0.046)